### ISSUE TITLE
显示迟钝、延迟问题

### ISSUE THREAD

**Issue by zyh941** [Xposed-Modules-Repo/fucking.internet.tile#1]
你好，开发者。我在用Pixel 5，运行原版Android 13系统，用上了你的这个插件后，虽然正常工作，但是会出现延迟显示问题：
1、比如说我开着流量和wifi（连上），然后我走远了离开这个wifi范围后，wifi磁贴那里还是显示我连着它，其实已经是断开并用上流量。如图
2、在连着WIFI后，流量磁贴也会出现延迟显示，如果是开着流量，点击时不会正常熄灭（但其实已经关闭成功），需要收回通知栏重新下拉才可能是新状态（也有可能不是），反之，如果是关着流量，点击时也会出现类似的问题。只有关闭WIFI后，流量磁贴才会正常实时显示状态。
麻烦看看是什么原因，是否有修复的可能性？
![Screenshot_20220905-193527](https://user-images.githubusercontent.com/95530307/188441426-95af4b36-74ba-4007-bc55-4543e688c876.png)

**Comment by YULIANGMAX** [comment]
我在使用中也发现到同样的问题。
其实移动数据和WLAN这两个磁贴功能都还在，只是被谷歌在显示时做了移除，插件只是让这两个被移除磁贴重新加入。
但是你描述的属于磁贴本身的功能问题，这个我无能为力。

已经被谷歌放弃的功能估计今后也不会再维护，也许终有一天这两个磁贴会被彻底移除。
